// Types actions USER

export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_SUCESS = 'USER_LOGIN_SUCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';
export const USER_SIGNUP_SUCESS = 'USER_SIGNUP_SUCESS';
export const USER_LOGOUT_SUCESS = 'USER_LOGOUT_SUCESS';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';
export const USER_FIND = 'USER_FIND';
export const USER_FIND_ERROR = 'USER_FIND_ERROR';

// Types actions Vehicle
export const LOADING_VEHICLES = 'LOADING_VEHICLES';
export const RESET_FORM = 'RESET_FORM';
export const SET_FIELD = 'SET_FIELD';
export const SET_ALL_FIELDS = 'SET_ALL_FIELDS';
export const SET_VEHICLES = 'SET_VEHICLES';
export const SET_VEHICLES_ERROR = 'SET_VEHICLES_ERROR';
export const VEHICLE_SAVED_SUCCESS = 'VEHICLE_SAVED_SUCCESS';
export const VEHICLE_SAVED_ERROR = 'VEHICLE_SAVED_ERROR';
export const VEHICLE_DELETED_SUCCESS = 'VEHICLE_DELETED_SUCCESS';
export const VEHICLE_DELETED_ERROR = 'VEHICLE_DELETED_ERROR';


// Type actions Images
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';
export const IMAGE_UPLOAD_COMPLETED = 'IMAGE_UPLOAD_COMPLETED';
export const SET_IMAGE = 'SET_IMAGE';
export const SET_ALL_IMAGE = 'SET_ALL_IMAGE';
export const RESET_IMAGES = 'RESET_IMAGES';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';