import { translate } from '../locales';

export default string = {
  LOGIN: translate('LOGIN'),
  SIGNUP1: translate('SIGNUP1'),
  SEND: translate('SEND'),
  SAVE: translate('SAVE'),
  DELETE: translate('DELETE'),
  EDIT: translate('EDIT'),
  CANCEL: translate('CANCEL'),
  CONCLUDE: translate('CONCLUDE'),
  SIGNUP2: translate('SIGNUP2'),
  FORGOT: translate('FORGOT'),
  DONT_HAVE: translate('DONT_HAVE'),
  HAVE: translate('HAVE'),

  USERNAME_LABEL: translate('USERNAME_LABEL'),
  EMAIL_LABEL: translate('EMAIL_LABEL'),
  PASSWORD_LABEL: translate('PASSWORD_LABEL'),
  CONFIRMPASSWORD_LABEL: translate('CONFIRMPASSWORD_LABEL'),
  LICENSE_PLATE_LABEL: translate('LICENSE_PLATE_LABEL'),
  MODEL_LABEL: translate('MODEL_LABEL'),
  DATE_HOUR_LABEL: translate('DATE_HOUR_LABEL'),
  TYPE_LABEL: translate('TYPE_LABEL'),
  COLOR_LABEL: translate('COLOR_LABEL'),

  USERNAME_PLACEHOLDER: translate('USERNAME_PLACEHOLDER'),
  EMAIL_PLACEHOLDER: translate('EMAIL_PLACEHOLDER'),
  PASSWORD_PLACEHOLDER: translate('PASSWORD_PLACEHOLDER'),
  CONFIRMPASSWORD_PLACEHOLDER: translate('CONFIRMPASSWORD_PLACEHOLDER'),
  LICENSE_PLATE_PLACEHOLDER: translate('LICENSE_PLATE_PLACEHOLDER'),
  MODEL_PLACEHOLDER: translate('MODEL_PLACEHOLDER'),
  DATE_HOUR_PLACEHOLDER: translate('DATE_HOUR_PLACEHOLDER'),

  USERNAME_MESSAGE: translate('USERNAME_MESSAGE'),
  EMAIL_MESSAGE: translate('EMAIL_MESSAGE'),
  PASSWORD_MESSAGE: translate('PASSWORD_MESSAGE'),
  CONFIRMPASSWORD_MESSAGE: translate('CONFIRMPASSWORD_MESSAGE'),
  PASSWORD_NOT_MATCH_MESSAGE: translate('PASSWORD_NOT_MATCH_MESSAGE'),

  LISTING: translate('LISTING'),
  REGISTER: translate('REGISTER'),
  DATE_TIME: translate('DATE_TIME'),

  WEAK_PASSWORD: translate('WEAK_PASSWORD'),
  USER_NOT_FOUND: translate('USER_NOT_FOUND'),
  WRONG_PASSWORD: translate('WRONG_PASSWORD'),
  INVALID_EMAIL: translate('INVALID_EMAIL')
}